package persistence

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// AfterBeginHook is the function shape fired by the persister at
// position A — INSIDE the TX, BEFORE any framework write (data row,
// outbox row, audit row). Returning a non-nil error rolls the TX back.
//
//   - ctx is the request-scoped *AppContext; it satisfies context.Context
//     so cancellation propagates to the hook's own SQL.
//   - t is the consumer's domain entity type (*User, *Order). Wrapper
//     metadata (Signature, ActionName, Events) is reachable via
//     BaseEntity-promoted methods on the entity itself.
//   - tx is the application-layer TxHandle the hook uses to write
//     companion rows or read state in the same TX as the framework.
//
// afterBegin has no id parameter because for Insert the id has not been
// generated yet, and for Update / Archive / Unarchive / Delete the id is
// already available via t.GetID() — duplicating it would be noise.
type AfterBeginHook[T any] func(ctx *configuration.AppContext, t T, tx TxHandle) error

// BeforeCommitHook is the function shape fired by the persister at
// position D — INSIDE the TX, AFTER all framework writes (data row,
// every child row, outbox row, audit row when configured) and BEFORE
// COMMIT. Returning a non-nil error rolls the TX back; the framework
// writes that already happened during the TX roll back with the hook's
// error.
//
//   - ctx / t / tx mirror AfterBeginHook.
//   - id carries the aggregate root identifier — generated by the data
//     write on Insert, known from the path on Update / Archive /
//     Unarchive / Delete. Present here because beforeCommit is the slot
//     that typically writes an extra outbox row keyed on the aggregate
//     id; receiving it on the signature avoids forcing every hook to
//     extract it from t each time.
type BeforeCommitHook[T any] func(ctx *configuration.AppContext, t T, id domain.ID, tx TxHandle) error

// AfterBeginHookProvider is the interface the Auto Command Handlers
// detect via type assertion on the Cmd. A Cmd that declares
//
//	func (c *InsertUserCommand) AfterBegin(
//	    ctx *configuration.AppContext, u *User, tx persistence.TxHandle,
//	) error
//
// satisfies the provider automatically; the handler reads the method
// value and threads it as WriteOption[T] to the Writer. The method name
// has no prefix — Go idiom for a struct method named after the event it
// responds to (mirrors Read/Close/Unwrap on stdlib interfaces). The
// counterpart functional option is persistence.WithAfterBegin[T] — the
// With* prefix is the functional-options idiom; each surface follows its
// own naming convention.
//
// Compile-time safety against typos is opt-in via
//
//	var _ persistence.AfterBeginHookProvider[*User] = (*InsertUserCommand)(nil)
//
// at the bottom of the Cmd file. The framework does not enforce the
// boilerplate.
type AfterBeginHookProvider[T any] interface {
	AfterBegin(ctx *configuration.AppContext, t T, tx TxHandle) error
}

// BeforeCommitHookProvider mirrors AfterBeginHookProvider for the
// beforeCommit slot. The recommended compile-time safety pattern is the
// same:
//
//	var _ persistence.BeforeCommitHookProvider[*User] = (*InsertUserCommand)(nil)
type BeforeCommitHookProvider[T any] interface {
	BeforeCommit(ctx *configuration.AppContext, t T, id domain.ID, tx TxHandle) error
}
