// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: omnicore/v1/query.proto

package omnicorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringOp mirrors the REST string operator vocabulary, case-sensitive and
// case-insensitive (I*) variants included.
type StringOp int32

const (
	StringOp_STRING_OP_UNSPECIFIED StringOp = 0
	StringOp_STRING_OP_EQ          StringOp = 1
	StringOp_STRING_OP_NE          StringOp = 2
	StringOp_STRING_OP_IN          StringOp = 3
	StringOp_STRING_OP_NIN         StringOp = 4
	StringOp_STRING_OP_STARTSWITH  StringOp = 5
	StringOp_STRING_OP_CONTAINS    StringOp = 6
	StringOp_STRING_OP_IEQ         StringOp = 7
	StringOp_STRING_OP_INE         StringOp = 8
	StringOp_STRING_OP_IIN         StringOp = 9
	StringOp_STRING_OP_ININ        StringOp = 10
	StringOp_STRING_OP_ISTARTSWITH StringOp = 11
	StringOp_STRING_OP_ICONTAINS   StringOp = 12
)

// Enum value maps for StringOp.
var (
	StringOp_name = map[int32]string{
		0:  "STRING_OP_UNSPECIFIED",
		1:  "STRING_OP_EQ",
		2:  "STRING_OP_NE",
		3:  "STRING_OP_IN",
		4:  "STRING_OP_NIN",
		5:  "STRING_OP_STARTSWITH",
		6:  "STRING_OP_CONTAINS",
		7:  "STRING_OP_IEQ",
		8:  "STRING_OP_INE",
		9:  "STRING_OP_IIN",
		10: "STRING_OP_ININ",
		11: "STRING_OP_ISTARTSWITH",
		12: "STRING_OP_ICONTAINS",
	}
	StringOp_value = map[string]int32{
		"STRING_OP_UNSPECIFIED": 0,
		"STRING_OP_EQ":          1,
		"STRING_OP_NE":          2,
		"STRING_OP_IN":          3,
		"STRING_OP_NIN":         4,
		"STRING_OP_STARTSWITH":  5,
		"STRING_OP_CONTAINS":    6,
		"STRING_OP_IEQ":         7,
		"STRING_OP_INE":         8,
		"STRING_OP_IIN":         9,
		"STRING_OP_ININ":        10,
		"STRING_OP_ISTARTSWITH": 11,
		"STRING_OP_ICONTAINS":   12,
	}
)

func (x StringOp) Enum() *StringOp {
	p := new(StringOp)
	*p = x
	return p
}

func (x StringOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StringOp) Descriptor() protoreflect.EnumDescriptor {
	return file_omnicore_v1_query_proto_enumTypes[0].Descriptor()
}

func (StringOp) Type() protoreflect.EnumType {
	return &file_omnicore_v1_query_proto_enumTypes[0]
}

func (x StringOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StringOp.Descriptor instead.
func (StringOp) EnumDescriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{0}
}

// NumberOp mirrors the REST numeric/date vocabulary — no case-insensitive
// variants by design (case-folding has no meaning on ordinal comparisons).
type NumberOp int32

const (
	NumberOp_NUMBER_OP_UNSPECIFIED NumberOp = 0
	NumberOp_NUMBER_OP_EQ          NumberOp = 1
	NumberOp_NUMBER_OP_NE          NumberOp = 2
	NumberOp_NUMBER_OP_IN          NumberOp = 3
	NumberOp_NUMBER_OP_NIN         NumberOp = 4
	NumberOp_NUMBER_OP_GT          NumberOp = 5
	NumberOp_NUMBER_OP_GTE         NumberOp = 6
	NumberOp_NUMBER_OP_LT          NumberOp = 7
	NumberOp_NUMBER_OP_LTE         NumberOp = 8
)

// Enum value maps for NumberOp.
var (
	NumberOp_name = map[int32]string{
		0: "NUMBER_OP_UNSPECIFIED",
		1: "NUMBER_OP_EQ",
		2: "NUMBER_OP_NE",
		3: "NUMBER_OP_IN",
		4: "NUMBER_OP_NIN",
		5: "NUMBER_OP_GT",
		6: "NUMBER_OP_GTE",
		7: "NUMBER_OP_LT",
		8: "NUMBER_OP_LTE",
	}
	NumberOp_value = map[string]int32{
		"NUMBER_OP_UNSPECIFIED": 0,
		"NUMBER_OP_EQ":          1,
		"NUMBER_OP_NE":          2,
		"NUMBER_OP_IN":          3,
		"NUMBER_OP_NIN":         4,
		"NUMBER_OP_GT":          5,
		"NUMBER_OP_GTE":         6,
		"NUMBER_OP_LT":          7,
		"NUMBER_OP_LTE":         8,
	}
)

func (x NumberOp) Enum() *NumberOp {
	p := new(NumberOp)
	*p = x
	return p
}

func (x NumberOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumberOp) Descriptor() protoreflect.EnumDescriptor {
	return file_omnicore_v1_query_proto_enumTypes[1].Descriptor()
}

func (NumberOp) Type() protoreflect.EnumType {
	return &file_omnicore_v1_query_proto_enumTypes[1]
}

func (x NumberOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumberOp.Descriptor instead.
func (NumberOp) EnumDescriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{1}
}

// BoolOp: equality only — anything else is meaningless on a boolean.
type BoolOp int32

const (
	BoolOp_BOOL_OP_UNSPECIFIED BoolOp = 0
	BoolOp_BOOL_OP_EQ          BoolOp = 1
	BoolOp_BOOL_OP_NE          BoolOp = 2
)

// Enum value maps for BoolOp.
var (
	BoolOp_name = map[int32]string{
		0: "BOOL_OP_UNSPECIFIED",
		1: "BOOL_OP_EQ",
		2: "BOOL_OP_NE",
	}
	BoolOp_value = map[string]int32{
		"BOOL_OP_UNSPECIFIED": 0,
		"BOOL_OP_EQ":          1,
		"BOOL_OP_NE":          2,
	}
)

func (x BoolOp) Enum() *BoolOp {
	p := new(BoolOp)
	*p = x
	return p
}

func (x BoolOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoolOp) Descriptor() protoreflect.EnumDescriptor {
	return file_omnicore_v1_query_proto_enumTypes[2].Descriptor()
}

func (BoolOp) Type() protoreflect.EnumType {
	return &file_omnicore_v1_query_proto_enumTypes[2]
}

func (x BoolOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoolOp.Descriptor instead.
func (BoolOp) EnumDescriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{2}
}

// PaginationRequest carries the read-side control keys — the proto siblings
// of ?after ?before ?limit ?onlyTotal ?includeArchived ?search. The
// conventional field name is `pagination`. `search` is honored only when the
// Request DTO opts in via `query:"search"` (the same gate the REST wire
// applies); setting it against a non-opted-in DTO rejects as SchemaViolation.
// Combining only_total=true with after/before/limit (or with sort/read_mask)
// rejects the same way — the REST conflict matrix, verbatim.
type PaginationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	After           *string                `protobuf:"bytes,1,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Before          *string                `protobuf:"bytes,2,opt,name=before,proto3,oneof" json:"before,omitempty"`
	Limit           *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	OnlyTotal       bool                   `protobuf:"varint,4,opt,name=only_total,json=onlyTotal,proto3" json:"only_total,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,5,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Search          *string                `protobuf:"bytes,6,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_omnicore_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *PaginationRequest) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

func (x *PaginationRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PaginationRequest) GetOnlyTotal() bool {
	if x != nil {
		return x.OnlyTotal
	}
	return false
}

func (x *PaginationRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *PaginationRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

// PaginationInfo is the response-side envelope — the exact mirror of the
// REST `pagination` block (same field names, same semantics; the
// conventional field name on the response message is `pagination`). A list
// response composes it next to ONE repeated message field (the items); the
// framework locates both BY TYPE, so item/field naming stays the service's
// choice. Cursors are opaque keyset cursors (echo them into
// PaginationRequest.after/before), empty when there is no further page —
// has_next/has_prev state the same fact as explicit booleans.
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	PrevCursor    string                 `protobuf:"bytes,3,opt,name=prev_cursor,json=prevCursor,proto3" json:"prev_cursor,omitempty"`
	HasNext       bool                   `protobuf:"varint,4,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,5,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_omnicore_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationInfo) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PaginationInfo) GetPrevCursor() string {
	if x != nil {
		return x.PrevCursor
	}
	return ""
}

func (x *PaginationInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationInfo) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

// SortField is one ?sort= entry: the WIRE field name (the response
// message's proto field, snake_case) + direction. The converter resolves it
// against the view's declared Fields vocabulary — an undeclared name is a
// wire-contract violation.
type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_omnicore_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// One condition = one operator application. A filter carries repeated
// conditions on the same field: they AND-combine (the proto sibling of
// ?age.gte=18&age.lte=65 — queries.MultiClause downstream). List operators
// (IN/NIN/IIN/ININ) consume every value; scalar operators consume values[0].
type StringCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            StringOp               `protobuf:"varint,1,opt,name=op,proto3,enum=omnicore.v1.StringOp" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringCondition) Reset() {
	*x = StringCondition{}
	mi := &file_omnicore_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringCondition) ProtoMessage() {}

func (x *StringCondition) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringCondition.ProtoReflect.Descriptor instead.
func (*StringCondition) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *StringCondition) GetOp() StringOp {
	if x != nil {
		return x.Op
	}
	return StringOp_STRING_OP_UNSPECIFIED
}

func (x *StringCondition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type StringFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*StringCondition     `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringFilter) Reset() {
	*x = StringFilter{}
	mi := &file_omnicore_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFilter) ProtoMessage() {}

func (x *StringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFilter.ProtoReflect.Descriptor instead.
func (*StringFilter) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *StringFilter) GetConditions() []*StringCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Int64Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            NumberOp               `protobuf:"varint,1,opt,name=op,proto3,enum=omnicore.v1.NumberOp" json:"op,omitempty"`
	Values        []int64                `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Condition) Reset() {
	*x = Int64Condition{}
	mi := &file_omnicore_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Condition) ProtoMessage() {}

func (x *Int64Condition) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Condition.ProtoReflect.Descriptor instead.
func (*Int64Condition) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *Int64Condition) GetOp() NumberOp {
	if x != nil {
		return x.Op
	}
	return NumberOp_NUMBER_OP_UNSPECIFIED
}

func (x *Int64Condition) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int64Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Int64Condition      `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Filter) Reset() {
	*x = Int64Filter{}
	mi := &file_omnicore_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Filter) ProtoMessage() {}

func (x *Int64Filter) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Filter.ProtoReflect.Descriptor instead.
func (*Int64Filter) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *Int64Filter) GetConditions() []*Int64Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type DoubleCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            NumberOp               `protobuf:"varint,1,opt,name=op,proto3,enum=omnicore.v1.NumberOp" json:"op,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleCondition) Reset() {
	*x = DoubleCondition{}
	mi := &file_omnicore_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleCondition) ProtoMessage() {}

func (x *DoubleCondition) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleCondition.ProtoReflect.Descriptor instead.
func (*DoubleCondition) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *DoubleCondition) GetOp() NumberOp {
	if x != nil {
		return x.Op
	}
	return NumberOp_NUMBER_OP_UNSPECIFIED
}

func (x *DoubleCondition) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type DoubleFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*DoubleCondition     `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleFilter) Reset() {
	*x = DoubleFilter{}
	mi := &file_omnicore_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleFilter) ProtoMessage() {}

func (x *DoubleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleFilter.ProtoReflect.Descriptor instead.
func (*DoubleFilter) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *DoubleFilter) GetConditions() []*DoubleCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type BoolCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            BoolOp                 `protobuf:"varint,1,opt,name=op,proto3,enum=omnicore.v1.BoolOp" json:"op,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolCondition) Reset() {
	*x = BoolCondition{}
	mi := &file_omnicore_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolCondition) ProtoMessage() {}

func (x *BoolCondition) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolCondition.ProtoReflect.Descriptor instead.
func (*BoolCondition) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *BoolCondition) GetOp() BoolOp {
	if x != nil {
		return x.Op
	}
	return BoolOp_BOOL_OP_UNSPECIFIED
}

func (x *BoolCondition) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type BoolFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*BoolCondition       `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolFilter) Reset() {
	*x = BoolFilter{}
	mi := &file_omnicore_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolFilter) ProtoMessage() {}

func (x *BoolFilter) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolFilter.ProtoReflect.Descriptor instead.
func (*BoolFilter) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *BoolFilter) GetConditions() []*BoolCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// TimestampCondition values convert to the RFC3339 string form the REST
// string-leaf coercion produces, so both wires filter date-carrying string
// columns identically.
type TimestampCondition struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Op            NumberOp                 `protobuf:"varint,1,opt,name=op,proto3,enum=omnicore.v1.NumberOp" json:"op,omitempty"`
	Values        []*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampCondition) Reset() {
	*x = TimestampCondition{}
	mi := &file_omnicore_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampCondition) ProtoMessage() {}

func (x *TimestampCondition) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampCondition.ProtoReflect.Descriptor instead.
func (*TimestampCondition) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *TimestampCondition) GetOp() NumberOp {
	if x != nil {
		return x.Op
	}
	return NumberOp_NUMBER_OP_UNSPECIFIED
}

func (x *TimestampCondition) GetValues() []*timestamppb.Timestamp {
	if x != nil {
		return x.Values
	}
	return nil
}

type TimestampFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*TimestampCondition  `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampFilter) Reset() {
	*x = TimestampFilter{}
	mi := &file_omnicore_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampFilter) ProtoMessage() {}

func (x *TimestampFilter) ProtoReflect() protoreflect.Message {
	mi := &file_omnicore_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampFilter.ProtoReflect.Descriptor instead.
func (*TimestampFilter) Descriptor() ([]byte, []int) {
	return file_omnicore_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *TimestampFilter) GetConditions() []*TimestampCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_omnicore_v1_query_proto protoreflect.FileDescriptor

const file_omnicore_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x17omnicore/v1/query.proto\x12\vomnicore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x11PaginationRequest\x12\x19\n" +
	"\x05after\x18\x01 \x01(\tH\x00R\x05after\x88\x01\x01\x12\x1b\n" +
	"\x06before\x18\x02 \x01(\tH\x01R\x06before\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x02R\x05limit\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"only_total\x18\x04 \x01(\bR\tonlyTotal\x12)\n" +
	"\x10include_archived\x18\x05 \x01(\bR\x0fincludeArchived\x12\x1b\n" +
	"\x06search\x18\x06 \x01(\tH\x03R\x06search\x88\x01\x01B\b\n" +
	"\x06_afterB\t\n" +
	"\a_beforeB\b\n" +
	"\x06_limitB\t\n" +
	"\a_search\"\x9e\x01\n" +
	"\x0ePaginationInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x1f\n" +
	"\vprev_cursor\x18\x03 \x01(\tR\n" +
	"prevCursor\x12\x19\n" +
	"\bhas_next\x18\x04 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x05 \x01(\bR\ahasPrev\"5\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"P\n" +
	"\x0fStringCondition\x12%\n" +
	"\x02op\x18\x01 \x01(\x0e2\x15.omnicore.v1.StringOpR\x02op\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"L\n" +
	"\fStringFilter\x12<\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1c.omnicore.v1.StringConditionR\n" +
	"conditions\"O\n" +
	"\x0eInt64Condition\x12%\n" +
	"\x02op\x18\x01 \x01(\x0e2\x15.omnicore.v1.NumberOpR\x02op\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x03R\x06values\"J\n" +
	"\vInt64Filter\x12;\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1b.omnicore.v1.Int64ConditionR\n" +
	"conditions\"P\n" +
	"\x0fDoubleCondition\x12%\n" +
	"\x02op\x18\x01 \x01(\x0e2\x15.omnicore.v1.NumberOpR\x02op\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\"L\n" +
	"\fDoubleFilter\x12<\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1c.omnicore.v1.DoubleConditionR\n" +
	"conditions\"J\n" +
	"\rBoolCondition\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.omnicore.v1.BoolOpR\x02op\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"H\n" +
	"\n" +
	"BoolFilter\x12:\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1a.omnicore.v1.BoolConditionR\n" +
	"conditions\"o\n" +
	"\x12TimestampCondition\x12%\n" +
	"\x02op\x18\x01 \x01(\x0e2\x15.omnicore.v1.NumberOpR\x02op\x122\n" +
	"\x06values\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\x06values\"R\n" +
	"\x0fTimestampFilter\x12?\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1f.omnicore.v1.TimestampConditionR\n" +
	"conditions*\xa1\x02\n" +
	"\bStringOp\x12\x19\n" +
	"\x15STRING_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTRING_OP_EQ\x10\x01\x12\x10\n" +
	"\fSTRING_OP_NE\x10\x02\x12\x10\n" +
	"\fSTRING_OP_IN\x10\x03\x12\x11\n" +
	"\rSTRING_OP_NIN\x10\x04\x12\x18\n" +
	"\x14STRING_OP_STARTSWITH\x10\x05\x12\x16\n" +
	"\x12STRING_OP_CONTAINS\x10\x06\x12\x11\n" +
	"\rSTRING_OP_IEQ\x10\a\x12\x11\n" +
	"\rSTRING_OP_INE\x10\b\x12\x11\n" +
	"\rSTRING_OP_IIN\x10\t\x12\x12\n" +
	"\x0eSTRING_OP_ININ\x10\n" +
	"\x12\x19\n" +
	"\x15STRING_OP_ISTARTSWITH\x10\v\x12\x17\n" +
	"\x13STRING_OP_ICONTAINS\x10\f*\xb8\x01\n" +
	"\bNumberOp\x12\x19\n" +
	"\x15NUMBER_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fNUMBER_OP_EQ\x10\x01\x12\x10\n" +
	"\fNUMBER_OP_NE\x10\x02\x12\x10\n" +
	"\fNUMBER_OP_IN\x10\x03\x12\x11\n" +
	"\rNUMBER_OP_NIN\x10\x04\x12\x10\n" +
	"\fNUMBER_OP_GT\x10\x05\x12\x11\n" +
	"\rNUMBER_OP_GTE\x10\x06\x12\x10\n" +
	"\fNUMBER_OP_LT\x10\a\x12\x11\n" +
	"\rNUMBER_OP_LTE\x10\b*A\n" +
	"\x06BoolOp\x12\x17\n" +
	"\x13BOOL_OP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"BOOL_OP_EQ\x10\x01\x12\x0e\n" +
	"\n" +
	"BOOL_OP_NE\x10\x02B<Z:github.com/ClaudioSchirmer/omnicore/web/grpc/pb;omnicorepbb\x06proto3"

var (
	file_omnicore_v1_query_proto_rawDescOnce sync.Once
	file_omnicore_v1_query_proto_rawDescData []byte
)

func file_omnicore_v1_query_proto_rawDescGZIP() []byte {
	file_omnicore_v1_query_proto_rawDescOnce.Do(func() {
		file_omnicore_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omnicore_v1_query_proto_rawDesc), len(file_omnicore_v1_query_proto_rawDesc)))
	})
	return file_omnicore_v1_query_proto_rawDescData
}

var file_omnicore_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_omnicore_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_omnicore_v1_query_proto_goTypes = []any{
	(StringOp)(0),                 // 0: omnicore.v1.StringOp
	(NumberOp)(0),                 // 1: omnicore.v1.NumberOp
	(BoolOp)(0),                   // 2: omnicore.v1.BoolOp
	(*PaginationRequest)(nil),     // 3: omnicore.v1.PaginationRequest
	(*PaginationInfo)(nil),        // 4: omnicore.v1.PaginationInfo
	(*SortField)(nil),             // 5: omnicore.v1.SortField
	(*StringCondition)(nil),       // 6: omnicore.v1.StringCondition
	(*StringFilter)(nil),          // 7: omnicore.v1.StringFilter
	(*Int64Condition)(nil),        // 8: omnicore.v1.Int64Condition
	(*Int64Filter)(nil),           // 9: omnicore.v1.Int64Filter
	(*DoubleCondition)(nil),       // 10: omnicore.v1.DoubleCondition
	(*DoubleFilter)(nil),          // 11: omnicore.v1.DoubleFilter
	(*BoolCondition)(nil),         // 12: omnicore.v1.BoolCondition
	(*BoolFilter)(nil),            // 13: omnicore.v1.BoolFilter
	(*TimestampCondition)(nil),    // 14: omnicore.v1.TimestampCondition
	(*TimestampFilter)(nil),       // 15: omnicore.v1.TimestampFilter
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_omnicore_v1_query_proto_depIdxs = []int32{
	0,  // 0: omnicore.v1.StringCondition.op:type_name -> omnicore.v1.StringOp
	6,  // 1: omnicore.v1.StringFilter.conditions:type_name -> omnicore.v1.StringCondition
	1,  // 2: omnicore.v1.Int64Condition.op:type_name -> omnicore.v1.NumberOp
	8,  // 3: omnicore.v1.Int64Filter.conditions:type_name -> omnicore.v1.Int64Condition
	1,  // 4: omnicore.v1.DoubleCondition.op:type_name -> omnicore.v1.NumberOp
	10, // 5: omnicore.v1.DoubleFilter.conditions:type_name -> omnicore.v1.DoubleCondition
	2,  // 6: omnicore.v1.BoolCondition.op:type_name -> omnicore.v1.BoolOp
	12, // 7: omnicore.v1.BoolFilter.conditions:type_name -> omnicore.v1.BoolCondition
	1,  // 8: omnicore.v1.TimestampCondition.op:type_name -> omnicore.v1.NumberOp
	16, // 9: omnicore.v1.TimestampCondition.values:type_name -> google.protobuf.Timestamp
	14, // 10: omnicore.v1.TimestampFilter.conditions:type_name -> omnicore.v1.TimestampCondition
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_omnicore_v1_query_proto_init() }
func file_omnicore_v1_query_proto_init() {
	if File_omnicore_v1_query_proto != nil {
		return
	}
	file_omnicore_v1_query_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omnicore_v1_query_proto_rawDesc), len(file_omnicore_v1_query_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omnicore_v1_query_proto_goTypes,
		DependencyIndexes: file_omnicore_v1_query_proto_depIdxs,
		EnumInfos:         file_omnicore_v1_query_proto_enumTypes,
		MessageInfos:      file_omnicore_v1_query_proto_msgTypes,
	}.Build()
	File_omnicore_v1_query_proto = out.File
	file_omnicore_v1_query_proto_goTypes = nil
	file_omnicore_v1_query_proto_depIdxs = nil
}
