// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,2,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Rating        *int32                 `protobuf:"varint,3,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGadgetRequest) Reset() {
	*x = CreateGadgetRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGadgetRequest) ProtoMessage() {}

func (x *CreateGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGadgetRequest.ProtoReflect.Descriptor instead.
func (*CreateGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGadgetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateGadgetRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *CreateGadgetRequest) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

type CreateGadgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGadgetResponse) Reset() {
	*x = CreateGadgetResponse{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGadgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGadgetResponse) ProtoMessage() {}

func (x *CreateGadgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGadgetResponse.ProtoReflect.Descriptor instead.
func (*CreateGadgetResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGadgetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGadgetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListGadgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameContains  *string                `protobuf:"bytes,1,opt,name=name_contains,json=nameContains,proto3,oneof" json:"name_contains,omitempty"`
	OnlyTotal     bool                   `protobuf:"varint,2,opt,name=only_total,json=onlyTotal,proto3" json:"only_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGadgetsRequest) Reset() {
	*x = ListGadgetsRequest{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGadgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGadgetsRequest) ProtoMessage() {}

func (x *ListGadgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGadgetsRequest.ProtoReflect.Descriptor instead.
func (*ListGadgetsRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListGadgetsRequest) GetNameContains() string {
	if x != nil && x.NameContains != nil {
		return *x.NameContains
	}
	return ""
}

func (x *ListGadgetsRequest) GetOnlyTotal() bool {
	if x != nil {
		return x.OnlyTotal
	}
	return false
}

type ListGadgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGadgetsResponse) Reset() {
	*x = ListGadgetsResponse{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGadgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGadgetsResponse) ProtoMessage() {}

func (x *ListGadgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGadgetsResponse.ProtoReflect.Descriptor instead.
func (*ListGadgetsResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *ListGadgetsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGadgetsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGadgetRequest) Reset() {
	*x = UpdateGadgetRequest{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGadgetRequest) ProtoMessage() {}

func (x *UpdateGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGadgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpdateGadgetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGadgetRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

type ArchiveGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveGadgetRequest) Reset() {
	*x = ArchiveGadgetRequest{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveGadgetRequest) ProtoMessage() {}

func (x *ArchiveGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveGadgetRequest.ProtoReflect.Descriptor instead.
func (*ArchiveGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type GetGadgetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGadgetRequest) Reset() {
	*x = GetGadgetRequest{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGadgetRequest) ProtoMessage() {}

func (x *GetGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGadgetRequest.ProtoReflect.Descriptor instead.
func (*GetGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *GetGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GetGadgetRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type GetGadgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGadgetResponse) Reset() {
	*x = GetGadgetResponse{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGadgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGadgetResponse) ProtoMessage() {}

func (x *GetGadgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGadgetResponse.ProtoReflect.Descriptor instead.
func (*GetGadgetResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *GetGadgetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGadgetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x14omnicore.grpctest.v1\"\x81\x01\n" +
	"\x13CreateGadgetRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x02 \x01(\tH\x01R\x04kind\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x03 \x01(\x05H\x02R\x06rating\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_kindB\t\n" +
	"\a_rating\":\n" +
	"\x14CreateGadgetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\x12ListGadgetsRequest\x12(\n" +
	"\rname_contains\x18\x01 \x01(\tH\x00R\fnameContains\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"only_total\x18\x02 \x01(\bR\tonlyTotalB\x10\n" +
	"\x0e_name_contains\"A\n" +
	"\x13ListGadgetsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"u\n" +
	"\x13UpdateGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tH\x02R\x04kind\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_kind\"2\n" +
	"\x14ArchiveGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"Y\n" +
	"\x10GetGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchivedB\x05\n" +
	"\x03_id\"7\n" +
	"\x11GetGadgetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB5Z3github.com/ClaudioSchirmer/omnicore/internal/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_test_proto_goTypes = []any{
	(*CreateGadgetRequest)(nil),  // 0: omnicore.grpctest.v1.CreateGadgetRequest
	(*CreateGadgetResponse)(nil), // 1: omnicore.grpctest.v1.CreateGadgetResponse
	(*ListGadgetsRequest)(nil),   // 2: omnicore.grpctest.v1.ListGadgetsRequest
	(*ListGadgetsResponse)(nil),  // 3: omnicore.grpctest.v1.ListGadgetsResponse
	(*UpdateGadgetRequest)(nil),  // 4: omnicore.grpctest.v1.UpdateGadgetRequest
	(*ArchiveGadgetRequest)(nil), // 5: omnicore.grpctest.v1.ArchiveGadgetRequest
	(*GetGadgetRequest)(nil),     // 6: omnicore.grpctest.v1.GetGadgetRequest
	(*GetGadgetResponse)(nil),    // 7: omnicore.grpctest.v1.GetGadgetResponse
}
var file_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{}
	file_test_proto_msgTypes[2].OneofWrappers = []any{}
	file_test_proto_msgTypes[4].OneofWrappers = []any{}
	file_test_proto_msgTypes[5].OneofWrappers = []any{}
	file_test_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
