// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test.proto

package testpb

import (
	pb "github.com/ClaudioSchirmer/omnicore/web/grpc/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Flavor int32

const (
	Flavor_FLAVOR_UNSPECIFIED Flavor = 0
	Flavor_FLAVOR_SWEET       Flavor = 1
	Flavor_FLAVOR_SALTY       Flavor = 2
)

// Enum value maps for Flavor.
var (
	Flavor_name = map[int32]string{
		0: "FLAVOR_UNSPECIFIED",
		1: "FLAVOR_SWEET",
		2: "FLAVOR_SALTY",
	}
	Flavor_value = map[string]int32{
		"FLAVOR_UNSPECIFIED": 0,
		"FLAVOR_SWEET":       1,
		"FLAVOR_SALTY":       2,
	}
)

func (x Flavor) Enum() *Flavor {
	p := new(Flavor)
	*p = x
	return p
}

func (x Flavor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flavor) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Flavor) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Flavor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flavor.Descriptor instead.
func (Flavor) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type CreateGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,2,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Rating        *int32                 `protobuf:"varint,3,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGadgetRequest) Reset() {
	*x = CreateGadgetRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGadgetRequest) ProtoMessage() {}

func (x *CreateGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGadgetRequest.ProtoReflect.Descriptor instead.
func (*CreateGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGadgetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateGadgetRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *CreateGadgetRequest) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

type CreateGadgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGadgetResponse) Reset() {
	*x = CreateGadgetResponse{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGadgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGadgetResponse) ProtoMessage() {}

func (x *CreateGadgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGadgetResponse.ProtoReflect.Descriptor instead.
func (*CreateGadgetResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGadgetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGadgetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListGadgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameContains  *string                `protobuf:"bytes,1,opt,name=name_contains,json=nameContains,proto3,oneof" json:"name_contains,omitempty"`
	OnlyTotal     bool                   `protobuf:"varint,2,opt,name=only_total,json=onlyTotal,proto3" json:"only_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGadgetsRequest) Reset() {
	*x = ListGadgetsRequest{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGadgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGadgetsRequest) ProtoMessage() {}

func (x *ListGadgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGadgetsRequest.ProtoReflect.Descriptor instead.
func (*ListGadgetsRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListGadgetsRequest) GetNameContains() string {
	if x != nil && x.NameContains != nil {
		return *x.NameContains
	}
	return ""
}

func (x *ListGadgetsRequest) GetOnlyTotal() bool {
	if x != nil {
		return x.OnlyTotal
	}
	return false
}

type ListGadgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGadgetsResponse) Reset() {
	*x = ListGadgetsResponse{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGadgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGadgetsResponse) ProtoMessage() {}

func (x *ListGadgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGadgetsResponse.ProtoReflect.Descriptor instead.
func (*ListGadgetsResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *ListGadgetsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGadgetsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGadgetRequest) Reset() {
	*x = UpdateGadgetRequest{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGadgetRequest) ProtoMessage() {}

func (x *UpdateGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGadgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpdateGadgetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGadgetRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

type ArchiveGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveGadgetRequest) Reset() {
	*x = ArchiveGadgetRequest{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveGadgetRequest) ProtoMessage() {}

func (x *ArchiveGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveGadgetRequest.ProtoReflect.Descriptor instead.
func (*ArchiveGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type ArchiveGadgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveGadgetResponse) Reset() {
	*x = ArchiveGadgetResponse{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveGadgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveGadgetResponse) ProtoMessage() {}

func (x *ArchiveGadgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveGadgetResponse.ProtoReflect.Descriptor instead.
func (*ArchiveGadgetResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

type SearchGadgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *pb.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OrderBy       []*pb.OrderByField     `protobuf:"bytes,2,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields        *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Filters       *SearchGadgetsFilters  `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGadgetsRequest) Reset() {
	*x = SearchGadgetsRequest{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGadgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGadgetsRequest) ProtoMessage() {}

func (x *SearchGadgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGadgetsRequest.ProtoReflect.Descriptor instead.
func (*SearchGadgetsRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *SearchGadgetsRequest) GetPagination() *pb.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchGadgetsRequest) GetOrderBy() []*pb.OrderByField {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *SearchGadgetsRequest) GetFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchGadgetsRequest) GetFilters() *SearchGadgetsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchGadgetsFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *pb.StringFilter       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rating        *pb.Int64Filter        `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Price         *pb.DoubleFilter       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Active        *pb.BoolFilter         `protobuf:"bytes,4,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *pb.TimestampFilter    `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGadgetsFilters) Reset() {
	*x = SearchGadgetsFilters{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGadgetsFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGadgetsFilters) ProtoMessage() {}

func (x *SearchGadgetsFilters) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGadgetsFilters.ProtoReflect.Descriptor instead.
func (*SearchGadgetsFilters) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *SearchGadgetsFilters) GetName() *pb.StringFilter {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SearchGadgetsFilters) GetRating() *pb.Int64Filter {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *SearchGadgetsFilters) GetPrice() *pb.DoubleFilter {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *SearchGadgetsFilters) GetActive() *pb.BoolFilter {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *SearchGadgetsFilters) GetCreatedAt() *pb.TimestampFilter {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GadgetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GadgetItem) Reset() {
	*x = GadgetItem{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GadgetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GadgetItem) ProtoMessage() {}

func (x *GadgetItem) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GadgetItem.ProtoReflect.Descriptor instead.
func (*GadgetItem) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *GadgetItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GadgetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GadgetItem) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

type SearchGadgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GadgetItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *pb.PaginationInfo     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGadgetsResponse) Reset() {
	*x = SearchGadgetsResponse{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGadgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGadgetsResponse) ProtoMessage() {}

func (x *SearchGadgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGadgetsResponse.ProtoReflect.Descriptor instead.
func (*SearchGadgetsResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *SearchGadgetsResponse) GetItems() []*GadgetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchGadgetsResponse) GetPagination() *pb.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MapCarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapCarrier) Reset() {
	*x = MapCarrier{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCarrier) ProtoMessage() {}

func (x *MapCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCarrier.ProtoReflect.Descriptor instead.
func (*MapCarrier) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *MapCarrier) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TimeCarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	When          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCarrier) Reset() {
	*x = TimeCarrier{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCarrier) ProtoMessage() {}

func (x *TimeCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCarrier.ProtoReflect.Descriptor instead.
func (*TimeCarrier) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *TimeCarrier) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

type MaskCarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskCarrier) Reset() {
	*x = MaskCarrier{}
	mi := &file_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskCarrier) ProtoMessage() {}

func (x *MaskCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskCarrier.ProtoReflect.Descriptor instead.
func (*MaskCarrier) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{13}
}

func (x *MaskCarrier) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

type ChildThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildThing) Reset() {
	*x = ChildThing{}
	mi := &file_test_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildThing) ProtoMessage() {}

func (x *ChildThing) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildThing.ProtoReflect.Descriptor instead.
func (*ChildThing) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{14}
}

func (x *ChildThing) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type ParentThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kids          []*ChildThing          `protobuf:"bytes,1,rep,name=kids,proto3" json:"kids,omitempty"`
	Favorite      *ChildThing            `protobuf:"bytes,2,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentThing) Reset() {
	*x = ParentThing{}
	mi := &file_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentThing) ProtoMessage() {}

func (x *ParentThing) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentThing.ProtoReflect.Descriptor instead.
func (*ParentThing) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{15}
}

func (x *ParentThing) GetKids() []*ChildThing {
	if x != nil {
		return x.Kids
	}
	return nil
}

func (x *ParentThing) GetFavorite() *ChildThing {
	if x != nil {
		return x.Favorite
	}
	return nil
}

type TwoGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *SearchGadgetsFilters  `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             *SearchGadgetsFilters  `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoGroupsRequest) Reset() {
	*x = TwoGroupsRequest{}
	mi := &file_test_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoGroupsRequest) ProtoMessage() {}

func (x *TwoGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoGroupsRequest.ProtoReflect.Descriptor instead.
func (*TwoGroupsRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{16}
}

func (x *TwoGroupsRequest) GetA() *SearchGadgetsFilters {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *TwoGroupsRequest) GetB() *SearchGadgetsFilters {
	if x != nil {
		return x.B
	}
	return nil
}

type TwoRepeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             []*GadgetItem          `protobuf:"bytes,1,rep,name=a,proto3" json:"a,omitempty"`
	B             []*GadgetItem          `protobuf:"bytes,2,rep,name=b,proto3" json:"b,omitempty"`
	Pagination    *pb.PaginationInfo     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoRepeatsResponse) Reset() {
	*x = TwoRepeatsResponse{}
	mi := &file_test_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoRepeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoRepeatsResponse) ProtoMessage() {}

func (x *TwoRepeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoRepeatsResponse.ProtoReflect.Descriptor instead.
func (*TwoRepeatsResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{17}
}

func (x *TwoRepeatsResponse) GetA() []*GadgetItem {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *TwoRepeatsResponse) GetB() []*GadgetItem {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *TwoRepeatsResponse) GetPagination() *pb.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type OnlyPaginationInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *pb.PaginationInfo     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlyPaginationInfoResponse) Reset() {
	*x = OnlyPaginationInfoResponse{}
	mi := &file_test_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlyPaginationInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlyPaginationInfoResponse) ProtoMessage() {}

func (x *OnlyPaginationInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlyPaginationInfoResponse.ProtoReflect.Descriptor instead.
func (*OnlyPaginationInfoResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{18}
}

func (x *OnlyPaginationInfoResponse) GetPagination() *pb.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type TwoPaginationInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GadgetItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	A             *pb.PaginationInfo     `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
	B             *pb.PaginationInfo     `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPaginationInfosResponse) Reset() {
	*x = TwoPaginationInfosResponse{}
	mi := &file_test_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPaginationInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPaginationInfosResponse) ProtoMessage() {}

func (x *TwoPaginationInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPaginationInfosResponse.ProtoReflect.Descriptor instead.
func (*TwoPaginationInfosResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{19}
}

func (x *TwoPaginationInfosResponse) GetItems() []*GadgetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TwoPaginationInfosResponse) GetA() *pb.PaginationInfo {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *TwoPaginationInfosResponse) GetB() *pb.PaginationInfo {
	if x != nil {
		return x.B
	}
	return nil
}

type GetGadgetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGadgetRequest) Reset() {
	*x = GetGadgetRequest{}
	mi := &file_test_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGadgetRequest) ProtoMessage() {}

func (x *GetGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGadgetRequest.ProtoReflect.Descriptor instead.
func (*GetGadgetRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{20}
}

func (x *GetGadgetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GetGadgetRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type GetGadgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGadgetResponse) Reset() {
	*x = GetGadgetResponse{}
	mi := &file_test_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGadgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGadgetResponse) ProtoMessage() {}

func (x *GetGadgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGadgetResponse.ProtoReflect.Descriptor instead.
func (*GetGadgetResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{21}
}

func (x *GetGadgetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGadgetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ScalarChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildBig      int64                  `protobuf:"varint,1,opt,name=child_big,json=childBig,proto3" json:"child_big,omitempty"`
	ChildLabel    string                 `protobuf:"bytes,2,opt,name=child_label,json=childLabel,proto3" json:"child_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarChild) Reset() {
	*x = ScalarChild{}
	mi := &file_test_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarChild) ProtoMessage() {}

func (x *ScalarChild) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarChild.ProtoReflect.Descriptor instead.
func (*ScalarChild) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{22}
}

func (x *ScalarChild) GetChildBig() int64 {
	if x != nil {
		return x.ChildBig
	}
	return 0
}

func (x *ScalarChild) GetChildLabel() string {
	if x != nil {
		return x.ChildLabel
	}
	return ""
}

type FlavorCarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flavor        Flavor                 `protobuf:"varint,1,opt,name=flavor,proto3,enum=omnicore.grpctest.v1.Flavor" json:"flavor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlavorCarrier) Reset() {
	*x = FlavorCarrier{}
	mi := &file_test_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlavorCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlavorCarrier) ProtoMessage() {}

func (x *FlavorCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlavorCarrier.ProtoReflect.Descriptor instead.
func (*FlavorCarrier) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{23}
}

func (x *FlavorCarrier) GetFlavor() Flavor {
	if x != nil {
		return x.Flavor
	}
	return Flavor_FLAVOR_UNSPECIFIED
}

type ScalarMatrix struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Big              int64                  `protobuf:"varint,1,opt,name=big,proto3" json:"big,omitempty"`
	SignedBig        int64                  `protobuf:"zigzag64,2,opt,name=signed_big,json=signedBig,proto3" json:"signed_big,omitempty"`
	FixedSignedBig   int64                  `protobuf:"fixed64,3,opt,name=fixed_signed_big,json=fixedSignedBig,proto3" json:"fixed_signed_big,omitempty"`
	UnsignedBig      uint64                 `protobuf:"varint,4,opt,name=unsigned_big,json=unsignedBig,proto3" json:"unsigned_big,omitempty"`
	FixedUnsignedBig uint64                 `protobuf:"fixed64,5,opt,name=fixed_unsigned_big,json=fixedUnsignedBig,proto3" json:"fixed_unsigned_big,omitempty"`
	Small            int32                  `protobuf:"varint,6,opt,name=small,proto3" json:"small,omitempty"`
	UnsignedSmall    uint32                 `protobuf:"varint,7,opt,name=unsigned_small,json=unsignedSmall,proto3" json:"unsigned_small,omitempty"`
	Ratio            float64                `protobuf:"fixed64,8,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Fraction         float32                `protobuf:"fixed32,9,opt,name=fraction,proto3" json:"fraction,omitempty"`
	Flag             bool                   `protobuf:"varint,10,opt,name=flag,proto3" json:"flag,omitempty"`
	Label            string                 `protobuf:"bytes,11,opt,name=label,proto3" json:"label,omitempty"`
	Blob             []byte                 `protobuf:"bytes,12,opt,name=blob,proto3" json:"blob,omitempty"`
	Flavor           Flavor                 `protobuf:"varint,13,opt,name=flavor,proto3,enum=omnicore.grpctest.v1.Flavor" json:"flavor,omitempty"`
	When             *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=when,proto3" json:"when,omitempty"`
	Bigs             []int64                `protobuf:"varint,15,rep,packed,name=bigs,proto3" json:"bigs,omitempty"`
	Labels           []string               `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty"`
	Child            *ScalarChild           `protobuf:"bytes,17,opt,name=child,proto3" json:"child,omitempty"`
	Children         []*ScalarChild         `protobuf:"bytes,18,rep,name=children,proto3" json:"children,omitempty"`
	MaybeBig         *int64                 `protobuf:"varint,19,opt,name=maybe_big,json=maybeBig,proto3,oneof" json:"maybe_big,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScalarMatrix) Reset() {
	*x = ScalarMatrix{}
	mi := &file_test_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarMatrix) ProtoMessage() {}

func (x *ScalarMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarMatrix.ProtoReflect.Descriptor instead.
func (*ScalarMatrix) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{24}
}

func (x *ScalarMatrix) GetBig() int64 {
	if x != nil {
		return x.Big
	}
	return 0
}

func (x *ScalarMatrix) GetSignedBig() int64 {
	if x != nil {
		return x.SignedBig
	}
	return 0
}

func (x *ScalarMatrix) GetFixedSignedBig() int64 {
	if x != nil {
		return x.FixedSignedBig
	}
	return 0
}

func (x *ScalarMatrix) GetUnsignedBig() uint64 {
	if x != nil {
		return x.UnsignedBig
	}
	return 0
}

func (x *ScalarMatrix) GetFixedUnsignedBig() uint64 {
	if x != nil {
		return x.FixedUnsignedBig
	}
	return 0
}

func (x *ScalarMatrix) GetSmall() int32 {
	if x != nil {
		return x.Small
	}
	return 0
}

func (x *ScalarMatrix) GetUnsignedSmall() uint32 {
	if x != nil {
		return x.UnsignedSmall
	}
	return 0
}

func (x *ScalarMatrix) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *ScalarMatrix) GetFraction() float32 {
	if x != nil {
		return x.Fraction
	}
	return 0
}

func (x *ScalarMatrix) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *ScalarMatrix) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ScalarMatrix) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *ScalarMatrix) GetFlavor() Flavor {
	if x != nil {
		return x.Flavor
	}
	return Flavor_FLAVOR_UNSPECIFIED
}

func (x *ScalarMatrix) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *ScalarMatrix) GetBigs() []int64 {
	if x != nil {
		return x.Bigs
	}
	return nil
}

func (x *ScalarMatrix) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ScalarMatrix) GetChild() *ScalarChild {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *ScalarMatrix) GetChildren() []*ScalarChild {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScalarMatrix) GetMaybeBig() int64 {
	if x != nil && x.MaybeBig != nil {
		return *x.MaybeBig
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x14omnicore.grpctest.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17omnicore/v1/query.proto\"\x81\x01\n" +
	"\x13CreateGadgetRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x02 \x01(\tH\x01R\x04kind\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x03 \x01(\x05H\x02R\x06rating\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_kindB\t\n" +
	"\a_rating\":\n" +
	"\x14CreateGadgetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\x12ListGadgetsRequest\x12(\n" +
	"\rname_contains\x18\x01 \x01(\tH\x00R\fnameContains\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"only_total\x18\x02 \x01(\bR\tonlyTotalB\x10\n" +
	"\x0e_name_contains\"A\n" +
	"\x13ListGadgetsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"u\n" +
	"\x13UpdateGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tH\x02R\x04kind\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_kind\"2\n" +
	"\x14ArchiveGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"\x17\n" +
	"\x15ArchiveGadgetResponse\"\x86\x02\n" +
	"\x14SearchGadgetsRequest\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.omnicore.v1.PaginationRequestR\n" +
	"pagination\x124\n" +
	"\border_by\x18\x02 \x03(\v2\x19.omnicore.v1.OrderByFieldR\aorderBy\x122\n" +
	"\x06fields\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\x06fields\x12D\n" +
	"\afilters\x18\x04 \x01(\v2*.omnicore.grpctest.v1.SearchGadgetsFiltersR\afilters\"\x96\x02\n" +
	"\x14SearchGadgetsFilters\x12-\n" +
	"\x04name\x18\x01 \x01(\v2\x19.omnicore.v1.StringFilterR\x04name\x120\n" +
	"\x06rating\x18\x02 \x01(\v2\x18.omnicore.v1.Int64FilterR\x06rating\x12/\n" +
	"\x05price\x18\x03 \x01(\v2\x19.omnicore.v1.DoubleFilterR\x05price\x12/\n" +
	"\x06active\x18\x04 \x01(\v2\x17.omnicore.v1.BoolFilterR\x06active\x12;\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1c.omnicore.v1.TimestampFilterR\tcreatedAt\"R\n" +
	"\n" +
	"GadgetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tH\x00R\x04kind\x88\x01\x01B\a\n" +
	"\x05_kind\"\x8c\x01\n" +
	"\x15SearchGadgetsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .omnicore.grpctest.v1.GadgetItemR\x05items\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.omnicore.v1.PaginationInfoR\n" +
	"pagination\"\x8d\x01\n" +
	"\n" +
	"MapCarrier\x12D\n" +
	"\x06labels\x18\x01 \x03(\v2,.omnicore.grpctest.v1.MapCarrier.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\vTimeCarrier\x12.\n" +
	"\x04when\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04when\"=\n" +
	"\vMaskCarrier\x12.\n" +
	"\x04mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\")\n" +
	"\n" +
	"ChildThing\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\"\x81\x01\n" +
	"\vParentThing\x124\n" +
	"\x04kids\x18\x01 \x03(\v2 .omnicore.grpctest.v1.ChildThingR\x04kids\x12<\n" +
	"\bfavorite\x18\x02 \x01(\v2 .omnicore.grpctest.v1.ChildThingR\bfavorite\"\x86\x01\n" +
	"\x10TwoGroupsRequest\x128\n" +
	"\x01a\x18\x01 \x01(\v2*.omnicore.grpctest.v1.SearchGadgetsFiltersR\x01a\x128\n" +
	"\x01b\x18\x02 \x01(\v2*.omnicore.grpctest.v1.SearchGadgetsFiltersR\x01b\"\xb1\x01\n" +
	"\x12TwoRepeatsResponse\x12.\n" +
	"\x01a\x18\x01 \x03(\v2 .omnicore.grpctest.v1.GadgetItemR\x01a\x12.\n" +
	"\x01b\x18\x02 \x03(\v2 .omnicore.grpctest.v1.GadgetItemR\x01b\x12;\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1b.omnicore.v1.PaginationInfoR\n" +
	"pagination\"Y\n" +
	"\x1aOnlyPaginationInfoResponse\x12;\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.omnicore.v1.PaginationInfoR\n" +
	"pagination\"\xaa\x01\n" +
	"\x1aTwoPaginationInfosResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .omnicore.grpctest.v1.GadgetItemR\x05items\x12)\n" +
	"\x01a\x18\x02 \x01(\v2\x1b.omnicore.v1.PaginationInfoR\x01a\x12)\n" +
	"\x01b\x18\x03 \x01(\v2\x1b.omnicore.v1.PaginationInfoR\x01b\"Y\n" +
	"\x10GetGadgetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchivedB\x05\n" +
	"\x03_id\"7\n" +
	"\x11GetGadgetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"K\n" +
	"\vScalarChild\x12\x1b\n" +
	"\tchild_big\x18\x01 \x01(\x03R\bchildBig\x12\x1f\n" +
	"\vchild_label\x18\x02 \x01(\tR\n" +
	"childLabel\"E\n" +
	"\rFlavorCarrier\x124\n" +
	"\x06flavor\x18\x01 \x01(\x0e2\x1c.omnicore.grpctest.v1.FlavorR\x06flavor\"\xa1\x05\n" +
	"\fScalarMatrix\x12\x10\n" +
	"\x03big\x18\x01 \x01(\x03R\x03big\x12\x1d\n" +
	"\n" +
	"signed_big\x18\x02 \x01(\x12R\tsignedBig\x12(\n" +
	"\x10fixed_signed_big\x18\x03 \x01(\x10R\x0efixedSignedBig\x12!\n" +
	"\funsigned_big\x18\x04 \x01(\x04R\vunsignedBig\x12,\n" +
	"\x12fixed_unsigned_big\x18\x05 \x01(\x06R\x10fixedUnsignedBig\x12\x14\n" +
	"\x05small\x18\x06 \x01(\x05R\x05small\x12%\n" +
	"\x0eunsigned_small\x18\a \x01(\rR\runsignedSmall\x12\x14\n" +
	"\x05ratio\x18\b \x01(\x01R\x05ratio\x12\x1a\n" +
	"\bfraction\x18\t \x01(\x02R\bfraction\x12\x12\n" +
	"\x04flag\x18\n" +
	" \x01(\bR\x04flag\x12\x14\n" +
	"\x05label\x18\v \x01(\tR\x05label\x12\x12\n" +
	"\x04blob\x18\f \x01(\fR\x04blob\x124\n" +
	"\x06flavor\x18\r \x01(\x0e2\x1c.omnicore.grpctest.v1.FlavorR\x06flavor\x12.\n" +
	"\x04when\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x04when\x12\x12\n" +
	"\x04bigs\x18\x0f \x03(\x03R\x04bigs\x12\x16\n" +
	"\x06labels\x18\x10 \x03(\tR\x06labels\x127\n" +
	"\x05child\x18\x11 \x01(\v2!.omnicore.grpctest.v1.ScalarChildR\x05child\x12=\n" +
	"\bchildren\x18\x12 \x03(\v2!.omnicore.grpctest.v1.ScalarChildR\bchildren\x12 \n" +
	"\tmaybe_big\x18\x13 \x01(\x03H\x00R\bmaybeBig\x88\x01\x01B\f\n" +
	"\n" +
	"_maybe_big*D\n" +
	"\x06Flavor\x12\x16\n" +
	"\x12FLAVOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFLAVOR_SWEET\x10\x01\x12\x10\n" +
	"\fFLAVOR_SALTY\x10\x02B5Z3github.com/ClaudioSchirmer/omnicore/internal/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_test_proto_goTypes = []any{
	(Flavor)(0),                        // 0: omnicore.grpctest.v1.Flavor
	(*CreateGadgetRequest)(nil),        // 1: omnicore.grpctest.v1.CreateGadgetRequest
	(*CreateGadgetResponse)(nil),       // 2: omnicore.grpctest.v1.CreateGadgetResponse
	(*ListGadgetsRequest)(nil),         // 3: omnicore.grpctest.v1.ListGadgetsRequest
	(*ListGadgetsResponse)(nil),        // 4: omnicore.grpctest.v1.ListGadgetsResponse
	(*UpdateGadgetRequest)(nil),        // 5: omnicore.grpctest.v1.UpdateGadgetRequest
	(*ArchiveGadgetRequest)(nil),       // 6: omnicore.grpctest.v1.ArchiveGadgetRequest
	(*ArchiveGadgetResponse)(nil),      // 7: omnicore.grpctest.v1.ArchiveGadgetResponse
	(*SearchGadgetsRequest)(nil),       // 8: omnicore.grpctest.v1.SearchGadgetsRequest
	(*SearchGadgetsFilters)(nil),       // 9: omnicore.grpctest.v1.SearchGadgetsFilters
	(*GadgetItem)(nil),                 // 10: omnicore.grpctest.v1.GadgetItem
	(*SearchGadgetsResponse)(nil),      // 11: omnicore.grpctest.v1.SearchGadgetsResponse
	(*MapCarrier)(nil),                 // 12: omnicore.grpctest.v1.MapCarrier
	(*TimeCarrier)(nil),                // 13: omnicore.grpctest.v1.TimeCarrier
	(*MaskCarrier)(nil),                // 14: omnicore.grpctest.v1.MaskCarrier
	(*ChildThing)(nil),                 // 15: omnicore.grpctest.v1.ChildThing
	(*ParentThing)(nil),                // 16: omnicore.grpctest.v1.ParentThing
	(*TwoGroupsRequest)(nil),           // 17: omnicore.grpctest.v1.TwoGroupsRequest
	(*TwoRepeatsResponse)(nil),         // 18: omnicore.grpctest.v1.TwoRepeatsResponse
	(*OnlyPaginationInfoResponse)(nil), // 19: omnicore.grpctest.v1.OnlyPaginationInfoResponse
	(*TwoPaginationInfosResponse)(nil), // 20: omnicore.grpctest.v1.TwoPaginationInfosResponse
	(*GetGadgetRequest)(nil),           // 21: omnicore.grpctest.v1.GetGadgetRequest
	(*GetGadgetResponse)(nil),          // 22: omnicore.grpctest.v1.GetGadgetResponse
	(*ScalarChild)(nil),                // 23: omnicore.grpctest.v1.ScalarChild
	(*FlavorCarrier)(nil),              // 24: omnicore.grpctest.v1.FlavorCarrier
	(*ScalarMatrix)(nil),               // 25: omnicore.grpctest.v1.ScalarMatrix
	nil,                                // 26: omnicore.grpctest.v1.MapCarrier.LabelsEntry
	(*pb.PaginationRequest)(nil),       // 27: omnicore.v1.PaginationRequest
	(*pb.OrderByField)(nil),            // 28: omnicore.v1.OrderByField
	(*fieldmaskpb.FieldMask)(nil),      // 29: google.protobuf.FieldMask
	(*pb.StringFilter)(nil),            // 30: omnicore.v1.StringFilter
	(*pb.Int64Filter)(nil),             // 31: omnicore.v1.Int64Filter
	(*pb.DoubleFilter)(nil),            // 32: omnicore.v1.DoubleFilter
	(*pb.BoolFilter)(nil),              // 33: omnicore.v1.BoolFilter
	(*pb.TimestampFilter)(nil),         // 34: omnicore.v1.TimestampFilter
	(*pb.PaginationInfo)(nil),          // 35: omnicore.v1.PaginationInfo
	(*timestamppb.Timestamp)(nil),      // 36: google.protobuf.Timestamp
}
var file_test_proto_depIdxs = []int32{
	27, // 0: omnicore.grpctest.v1.SearchGadgetsRequest.pagination:type_name -> omnicore.v1.PaginationRequest
	28, // 1: omnicore.grpctest.v1.SearchGadgetsRequest.order_by:type_name -> omnicore.v1.OrderByField
	29, // 2: omnicore.grpctest.v1.SearchGadgetsRequest.fields:type_name -> google.protobuf.FieldMask
	9,  // 3: omnicore.grpctest.v1.SearchGadgetsRequest.filters:type_name -> omnicore.grpctest.v1.SearchGadgetsFilters
	30, // 4: omnicore.grpctest.v1.SearchGadgetsFilters.name:type_name -> omnicore.v1.StringFilter
	31, // 5: omnicore.grpctest.v1.SearchGadgetsFilters.rating:type_name -> omnicore.v1.Int64Filter
	32, // 6: omnicore.grpctest.v1.SearchGadgetsFilters.price:type_name -> omnicore.v1.DoubleFilter
	33, // 7: omnicore.grpctest.v1.SearchGadgetsFilters.active:type_name -> omnicore.v1.BoolFilter
	34, // 8: omnicore.grpctest.v1.SearchGadgetsFilters.created_at:type_name -> omnicore.v1.TimestampFilter
	10, // 9: omnicore.grpctest.v1.SearchGadgetsResponse.items:type_name -> omnicore.grpctest.v1.GadgetItem
	35, // 10: omnicore.grpctest.v1.SearchGadgetsResponse.pagination:type_name -> omnicore.v1.PaginationInfo
	26, // 11: omnicore.grpctest.v1.MapCarrier.labels:type_name -> omnicore.grpctest.v1.MapCarrier.LabelsEntry
	36, // 12: omnicore.grpctest.v1.TimeCarrier.when:type_name -> google.protobuf.Timestamp
	29, // 13: omnicore.grpctest.v1.MaskCarrier.mask:type_name -> google.protobuf.FieldMask
	15, // 14: omnicore.grpctest.v1.ParentThing.kids:type_name -> omnicore.grpctest.v1.ChildThing
	15, // 15: omnicore.grpctest.v1.ParentThing.favorite:type_name -> omnicore.grpctest.v1.ChildThing
	9,  // 16: omnicore.grpctest.v1.TwoGroupsRequest.a:type_name -> omnicore.grpctest.v1.SearchGadgetsFilters
	9,  // 17: omnicore.grpctest.v1.TwoGroupsRequest.b:type_name -> omnicore.grpctest.v1.SearchGadgetsFilters
	10, // 18: omnicore.grpctest.v1.TwoRepeatsResponse.a:type_name -> omnicore.grpctest.v1.GadgetItem
	10, // 19: omnicore.grpctest.v1.TwoRepeatsResponse.b:type_name -> omnicore.grpctest.v1.GadgetItem
	35, // 20: omnicore.grpctest.v1.TwoRepeatsResponse.pagination:type_name -> omnicore.v1.PaginationInfo
	35, // 21: omnicore.grpctest.v1.OnlyPaginationInfoResponse.pagination:type_name -> omnicore.v1.PaginationInfo
	10, // 22: omnicore.grpctest.v1.TwoPaginationInfosResponse.items:type_name -> omnicore.grpctest.v1.GadgetItem
	35, // 23: omnicore.grpctest.v1.TwoPaginationInfosResponse.a:type_name -> omnicore.v1.PaginationInfo
	35, // 24: omnicore.grpctest.v1.TwoPaginationInfosResponse.b:type_name -> omnicore.v1.PaginationInfo
	0,  // 25: omnicore.grpctest.v1.FlavorCarrier.flavor:type_name -> omnicore.grpctest.v1.Flavor
	0,  // 26: omnicore.grpctest.v1.ScalarMatrix.flavor:type_name -> omnicore.grpctest.v1.Flavor
	36, // 27: omnicore.grpctest.v1.ScalarMatrix.when:type_name -> google.protobuf.Timestamp
	23, // 28: omnicore.grpctest.v1.ScalarMatrix.child:type_name -> omnicore.grpctest.v1.ScalarChild
	23, // 29: omnicore.grpctest.v1.ScalarMatrix.children:type_name -> omnicore.grpctest.v1.ScalarChild
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{}
	file_test_proto_msgTypes[2].OneofWrappers = []any{}
	file_test_proto_msgTypes[4].OneofWrappers = []any{}
	file_test_proto_msgTypes[5].OneofWrappers = []any{}
	file_test_proto_msgTypes[9].OneofWrappers = []any{}
	file_test_proto_msgTypes[20].OneofWrappers = []any{}
	file_test_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
